apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: glance
        image: glanceapp/glance:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
